In [3]:
from PIL import Image
import numpy as np

In [42]:
%load_ext autoreload
%autoreload 2

In [15]:
x = np.array(Image.open('../image/jerem.jfif').convert('L'))
h = 1/16 * np.array([[1,2,1],
                     [2,4,2],
                     [1,2,1]])

In [43]:
from algorithme.admmp2 import ADMMP2

In [46]:
y = algo.gaussian_filter_2d()

In [56]:
from scipy import sparse, fft

In [67]:
R = np.eye(x.shape[0], x.shape[1])

In [139]:
algo = ADMMP2(x, h, R, 0.5, 0.2, 0.4)

In [152]:
algo.fit_transform(y/ 255.)

/home/heez/Documents/GitHub/Image_Restoration_SDI/src/algorithme/admmp2.py:174: RuntimeWarning: invalid value encountered in scalar divide
  tabTime.append(time()-timeRef)


(array([[-1.52199782e+211,  1.52199782e+211, -1.52199782e+211, ...,
          1.52199782e+211, -1.52199782e+211,  1.52199782e+211],
        [ 1.52199782e+211, -1.52199782e+211,  1.52199782e+211, ...,
         -1.52199782e+211,  1.52199782e+211, -1.52199782e+211],
        [-1.52199782e+211,  1.52199782e+211, -1.52199782e+211, ...,
          1.52199782e+211, -1.52199782e+211,  1.52199782e+211],
        ...,
        [ 1.52199782e+211, -1.52199782e+211,  1.52199782e+211, ...,
         -1.52199782e+211,  1.52199782e+211, -1.52199782e+211],
        [-1.52199782e+211,  1.52199782e+211, -1.52199782e+211, ...,
          1.52199782e+211, -1.52199782e+211,  1.52199782e+211],
        [ 1.52199782e+211, -1.52199782e+211,  1.52199782e+211, ...,
         -1.52199782e+211,  1.52199782e+211, -1.52199782e+211]]),
 5,
 [1.1622289103090892e+29,
  3.0575725215412155e+36,
  3.057572521541342e+36,
  3.0575725215412067e+36,
  inf],
 [0.26114559173583984,
  0.5508737564086914,
  0.8397338390350342,
  1.0429775

In [96]:
f, v = algo._precompute_matrix(x, y, 0.3)

In [185]:
X_, _,_,_ = algo.fit_transform(y)

/home/heez/Documents/GitHub/Image_Restoration_SDI/src/algorithme/admmp2.py:174: RuntimeWarning: invalid value encountered in scalar divide
  err = np.linalg.norm(x_ - x) / np.linalg.norm(x)


In [186]:
X_

array([[-3.88109443e+213,  3.88109443e+213, -3.88109443e+213, ...,
         3.88109443e+213, -3.88109443e+213,  3.88109443e+213],
       [ 3.88109443e+213, -3.88109443e+213,  3.88109443e+213, ...,
        -3.88109443e+213,  3.88109443e+213, -3.88109443e+213],
       [-3.88109443e+213,  3.88109443e+213, -3.88109443e+213, ...,
         3.88109443e+213, -3.88109443e+213,  3.88109443e+213],
       ...,
       [ 3.88109443e+213, -3.88109443e+213,  3.88109443e+213, ...,
        -3.88109443e+213,  3.88109443e+213, -3.88109443e+213],
       [-3.88109443e+213,  3.88109443e+213, -3.88109443e+213, ...,
         3.88109443e+213, -3.88109443e+213,  3.88109443e+213],
       [ 3.88109443e+213, -3.88109443e+213,  3.88109443e+213, ...,
        -3.88109443e+213,  3.88109443e+213, -3.88109443e+213]])

In [188]:
xref = x

In [193]:

pre_comput_Ty, inv_Tmu = algo._precompute_matrix(xref, y, algo.mu)
eta0, eta1 = np.zeros(xref.shape),  np.zeros(xref.shape)
x = pre_comput_Ty
u0 = inv_Tmu @ (pre_comput_Ty + algo.mu * (algo.A_dot(x) + eta0))
u1 = algo._shrink(x + eta1, algo.lambd/(algo.mu*algo.nu))
x_ = algo.H_inv_dot(algo.A_dot_adj((u0 - eta0)) + algo.nu * (u1 - eta1))

In [201]:
algo.inv_H @ algo.A_dot_adj((u0 - eta0)) + algo.nu * (u1 - eta1)

array([[ 1.64377617e+18-8.24883505e+17j,  2.40816448e+18-1.16524003e+18j,
         2.58112416e+18-1.21045690e+18j, ...,
         9.25940658e+17-7.90058665e+17j,  3.83556811e+17-3.31194894e+17j,
         5.65518510e+17-3.14604228e+17j],
       [-2.39054221e+16-5.03578967e+17j, -5.52635307e+15-7.62987332e+17j,
         2.46112209e+16-8.31726878e+17j, ...,
        -1.40873972e+17-1.54532992e+17j, -6.02054206e+16-6.47431080e+16j,
        -2.20392121e+16-1.61394298e+17j],
       [ 7.30173682e+17+1.59746090e+17j,  9.75227823e+17+2.47401037e+17j,
         9.82782658e+17+2.64195985e+17j, ...,
         9.05709999e+17-5.87675670e+16j,  3.81902948e+17-2.51621308e+16j,
         2.99569867e+17+4.21230672e+16j],
       ...,
       [-6.99766022e+16-2.57586108e+16j, -9.87354269e+16-5.61986710e+16j,
        -1.05381062e+17-7.01532988e+16j, ...,
        -1.01812910e+17+8.40698825e+16j, -4.28184799e+16+3.42636105e+16j,
        -2.94774455e+16-2.14893123e+14j],
       [-4.79293488e+17+4.00873777e+17j, -6.

In [192]:
u1

array([[60058.25  , 60012.3125, 59919.9375, ..., 59454.5   , 59576.1875,
        59827.0625],
       [59827.0625, 60058.25  , 60012.3125, ..., 59332.9375, 59454.5   ,
        59576.1875],
       [59576.1875, 59827.0625, 60058.25  , ..., 59179.0625, 59332.9375,
        59454.5   ],
       ...,
       [59959.625 , 60028.3125, 60095.125 , ..., 60058.25  , 60012.3125,
        59919.9375],
       [59919.9375, 59959.625 , 60028.3125, ..., 59827.0625, 60058.25  ,
        60012.3125],
       [60012.3125, 59919.9375, 59959.625 , ..., 59576.1875, 59827.0625,
        60058.25  ]])